/**
 * Context source catalog - EXAMPLE / template (SPEC-CONTEXT-SOURCES-AND-STORES).
 *
 * This tracked file is the shipped illustration and the fallback when no local catalog exists. It
 * names only sources this platform can ALREADY satisfy on a fresh deploy, built from the identifiers
 * the stack passes in - so it is correct out of the box rather than a set of placeholders someone has
 * to notice and replace.
 *
 * To define your OWN sources, copy this to `context-sources.local.ts` (GITIGNORED) and edit that.
 * Do not edit this file: it is tracked, so your changes would conflict on every upgrade, and your
 * deployment's specifics would live inside the generic artifact. Same posture as
 * `backend/deploy.config.json` and `.githooks/privacy-denylist`.
 *
 *     cp lib/config/context-sources.example.ts lib/config/context-sources.local.ts
 *
 * Entries are returned PER CLASSIFICATION, and that is the isolation boundary: a classification's
 * catalog is the complete set of sources a profile bound to it may name. Returning a source only for
 * `premium` means a `basic` profile cannot reference it, and the per-entry IAM grant the stack emits
 * means it could not read it even if it did.
 *
 * The reserved keys (`user-profile`, `company-docs`, `conversation`, `open-work`) carry fixed field
 * contracts - satisfy them and a profile written elsewhere works here. Anything else must start `x-`.
 */
import type { CatalogDeploymentContext, ContextSourceEntry } from './context-sources';

export function contextSourceCatalog(ctx: CatalogDeploymentContext): ContextSourceEntry[] {
  return [
    {
      key: 'company-docs',
      title: 'Company knowledge',
      description: 'Titles and one-line summaries of the documents this classification may read',
      useWhen: 'Deciding whether an answer exists in company knowledge before answering generally',
      type: 's3-prefix',
      arn: ctx.attachmentsBucketArn,
      locator: ctx.attachmentsBucketName,
      // The classification's OWN prefix, which is what makes this the isolation boundary: the grant
      // the stack emits names this exact path, so a lower classification cannot reach a higher one's.
      prefix: `context/${ctx.classification}/`,
      trust: 'operator',
      availability: 'always',
      maxBytes: 16384,
      fields: {
        digest: {
          type: 'string',
          // The digest ADR-017 already builds at this exact key. Without `from`, a generic reader
          // would have to guess `digest.json`, which does not exist.
          from: '_digest.json',
          description: 'The per-classification document menu (title + one-liner each)',
        },
      },
      contractVersion: '1.0',
    },
    {
      key: 'user-profile',
      title: 'About this person',
      description: 'Who the signed-in user is and what they told us during onboarding',
      useWhen: 'Personalising a greeting, or tailoring an answer to their company or role',
      // The BUILT-IN store is a DynamoDB table. An implementer swapping in their own service via
      // USER_PROFILE_SERVICE_ARN would change this entry to `lambda-service` with that ARN.
      type: 'dynamodb-table',
      arn: ctx.userProfileTableArn,
      locator: ctx.userProfileTableName,
      trust: 'platform',
      // NOT readable at WelcomeIntent: that fires on the assistant's channel membership, before the
      // creator's membership settles. Marked so the welcome omits it rather than waiting on it.
      availability: 'identity-settled',
      maxBytes: 4096,
      // The built-in store writes `{ userSub, onboardedAt, facts: {…}, updatedAt }` - every collected
      // answer lives UNDER `facts`, keyed by the intake field key. So each field names a dotted path.
      // Declaring them top-level (as this once did) found nothing and resolved the whole source to
      // absent on every turn, for every user.
      //
      // Which keys exist under `facts` is decided by THIS deployment's onboarding intake config, so
      // adjust these paths to match your own intake fields. A path that is not collected simply
      // resolves absent, which the outcome metric now reports rather than hiding.
      fields: {
        displayName: { type: 'string', from: 'facts.name', description: 'Preferred name for addressing them' },
        company: { type: 'string', optional: true, from: 'facts.company', description: 'Employer they gave at onboarding' },
        role: { type: 'string', optional: true, from: 'facts.role', description: 'Their job role, not their role in this conversation' },
      },
      contractVersion: '1.0',
    },
  ];
}
