import * as cdk from 'aws-cdk-lib';
import { apiAccessLogConfig } from '../constructs/api-access-logging';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as apigateway from 'aws-cdk-lib/aws-apigateway';
import * as cognito from 'aws-cdk-lib/aws-cognito';
import * as ssm from 'aws-cdk-lib/aws-ssm';
import { Construct } from 'constructs';

export interface S3StorageStackProps extends cdk.StackProps {
  appInstanceArn: string;
  userPool: cognito.IUserPool;
  /**
   * The admin-PLANE credential-exchange role ARN. Granted `s3:GetObject` on the assistant-
   * generated-doc and user-upload key prefixes so the exchange can vend a per-channel-scoped
   * attachment-read session policy for admin conversation review (the ceiling that policy
   * intersects). The grant lives here (with the bucket) to avoid a circular stack dep, mirroring
   * the execute-api teeth pattern.
   */
  exchangeRoleAdminPlaneArn?: string;
  /** SSM parameter NAME to publish the bucket ARN to, for the exchange to resolve at runtime. */
  attachmentsBucketArnParam?: string;
}

export class S3StorageStack extends cdk.Stack {
  public readonly attachmentsBucket: s3.Bucket;
  public readonly presignedUrlFunction: lambda.Function;

  constructor(scope: Construct, id: string, props: S3StorageStackProps) {
    super(scope, id, props);

    // Create S3 bucket for file attachments
    this.attachmentsBucket = new s3.Bucket(this, 'AttachmentsBucket', {
      // Bucket name auto-generated by CDK to avoid conflicts
      encryption: s3.BucketEncryption.S3_MANAGED,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      enforceSSL: true, // deny non-TLS access (aws:SecureTransport)
      versioned: true,
      removalPolicy: cdk.RemovalPolicy.RETAIN, // Keep bucket on stack deletion
      autoDeleteObjects: false, // Don't auto-delete objects
      lifecycleRules: [
        {
          id: 'DeleteOldVersions',
          noncurrentVersionExpiration: cdk.Duration.days(30),
        },
        {
          id: 'DeleteOldAttachments',
          expiration: cdk.Duration.days(90), // Keep attachments for 90 days
        },
      ],
      cors: [
        {
          allowedMethods: [
            s3.HttpMethods.GET,
            s3.HttpMethods.PUT,
            s3.HttpMethods.POST,
          ],
          allowedOrigins: [scope.node.tryGetContext('appUrl') || 'http://localhost:5173'],
          allowedHeaders: ['*'],
          maxAge: 3000,
        },
      ],
    });

    // Admin conversation attachment review (SPEC-ADMIN-IDENTITY / SPEC-CREDENTIAL-EXCHANGE):
    // grant the admin-plane exchange role `s3:GetObject` on the two attachment key families —
    //   generated-docs/*  the assistant's DELIVERABLES (reports/extractions), archive-read grade
    //   attachments/*      USER-UPLOADED input (may carry PII), moderation grade
    // This is the CEILING; the exchange's per-request session policy narrows to a single channel's
    // keys and picks the prefix per capability (attachment-read vs attachment-read-uploads), so the
    // generated-vs-uploaded split is IAM-enforceable. Publish the bucket ARN to SSM so the exchange
    // (created before this stack, so no CDK prop) resolves it at cold start.
    if (props.exchangeRoleAdminPlaneArn) {
      const adminPlaneRole = iam.Role.fromRoleArn(this, 'ImportedExchangeAdminPlaneRole', props.exchangeRoleAdminPlaneArn, {
        mutable: true,
      });
      adminPlaneRole.addToPrincipalPolicy(new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['s3:GetObject'],
        resources: [
          this.attachmentsBucket.arnForObjects('generated-docs/*'),
          this.attachmentsBucket.arnForObjects('attachments/*'),
        ],
      }));
    }
    if (props.attachmentsBucketArnParam) {
      new ssm.StringParameter(this, 'AttachmentsBucketArnParam', {
        parameterName: props.attachmentsBucketArnParam,
        stringValue: this.attachmentsBucket.bucketArn,
        description: 'Attachments bucket ARN — resolved by the credential exchange for the S3 attachment-read session policy',
      });
    }

    // Lambda function to generate presigned URLs
    this.presignedUrlFunction = new lambda.Function(this, 'PresignedUrlFunction', {
      runtime: lambda.Runtime.NODEJS_20_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset('lambda/presigned-url'),
      timeout: cdk.Duration.seconds(10),
      environment: {
        BUCKET_NAME: this.attachmentsBucket.bucketName,
        EXPIRATION_SECONDS: '3600', // 1 hour
        ALLOWED_ORIGIN: this.node.tryGetContext('appUrl') || 'http://localhost:5173',
      },
    });

    // Grant Lambda permissions to generate presigned URLs
    this.attachmentsBucket.grantReadWrite(this.presignedUrlFunction);

    // API Gateway with Cognito authorizer for presigned URL requests
    const appUrl = this.node.tryGetContext('appUrl') || 'http://localhost:5173';

    const authorizer = new apigateway.CognitoUserPoolsAuthorizer(this, 'PresignedUrlAuthorizer', {
      cognitoUserPools: [props.userPool],
    });

    const api = new apigateway.RestApi(this, 'PresignedUrlApi', {
      restApiName: 'AgentEchelon Presigned URL API',
      description: 'Authenticated API for generating S3 presigned URLs',
      defaultCorsPreflightOptions: {
        allowOrigins: [appUrl],
        allowMethods: ['POST', 'OPTIONS'],
        allowHeaders: ['Content-Type', 'Authorization'],
      },
      deployOptions: {
        throttlingBurstLimit: 50,
        throttlingRateLimit: 25,
        // Access logging.
        ...apiAccessLogConfig(this, 'PresignedUrlApiAccessLogs'),
      },
    });

    const presignedUrlIntegration = new apigateway.LambdaIntegration(this.presignedUrlFunction);
    api.root.addResource('presigned-url').addMethod('POST', presignedUrlIntegration, {
      authorizer,
      authorizationType: apigateway.AuthorizationType.COGNITO,
    });

    // Outputs
    new cdk.CfnOutput(this, 'AttachmentsBucketName', {
      value: this.attachmentsBucket.bucketName,
      description: 'S3 bucket for file attachments',
      exportName: `${this.stackName}-BucketName`,
    });

    new cdk.CfnOutput(this, 'PresignedUrlApiUrl', {
      value: `${api.url}presigned-url`,
      description: 'API Gateway URL for presigned URL generation',
      exportName: `${this.stackName}-PresignedUrlApiUrl`,
    });

    cdk.Tags.of(this).add('Component', 'S3Storage');
  }
}
