import * as cdk from 'aws-cdk-lib';
import { apiAccessLogConfig } from '../constructs/api-access-logging';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as apigateway from 'aws-cdk-lib/aws-apigateway';
import * as cognito from 'aws-cdk-lib/aws-cognito';
import { Construct } from 'constructs';

export interface S3StorageStackProps extends cdk.StackProps {
  appInstanceArn: string;
  userPool: cognito.IUserPool;
}

export class S3StorageStack extends cdk.Stack {
  public readonly attachmentsBucket: s3.Bucket;
  public readonly presignedUrlFunction: lambda.Function;

  constructor(scope: Construct, id: string, props: S3StorageStackProps) {
    super(scope, id, props);

    // Create S3 bucket for file attachments
    this.attachmentsBucket = new s3.Bucket(this, 'AttachmentsBucket', {
      // Bucket name auto-generated by CDK to avoid conflicts
      encryption: s3.BucketEncryption.S3_MANAGED,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      enforceSSL: true, // deny non-TLS access (aws:SecureTransport)
      versioned: true,
      removalPolicy: cdk.RemovalPolicy.RETAIN, // Keep bucket on stack deletion
      autoDeleteObjects: false, // Don't auto-delete objects
      lifecycleRules: [
        {
          id: 'DeleteOldVersions',
          noncurrentVersionExpiration: cdk.Duration.days(30),
        },
        {
          id: 'DeleteOldAttachments',
          expiration: cdk.Duration.days(90), // Keep attachments for 90 days
        },
      ],
      cors: [
        {
          allowedMethods: [
            s3.HttpMethods.GET,
            s3.HttpMethods.PUT,
            s3.HttpMethods.POST,
          ],
          allowedOrigins: [scope.node.tryGetContext('appUrl') || 'http://localhost:5173'],
          allowedHeaders: ['*'],
          maxAge: 3000,
        },
      ],
    });

    // Lambda function to generate presigned URLs
    this.presignedUrlFunction = new lambda.Function(this, 'PresignedUrlFunction', {
      runtime: lambda.Runtime.NODEJS_20_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset('lambda/presigned-url'),
      timeout: cdk.Duration.seconds(10),
      environment: {
        BUCKET_NAME: this.attachmentsBucket.bucketName,
        EXPIRATION_SECONDS: '3600', // 1 hour
        ALLOWED_ORIGIN: this.node.tryGetContext('appUrl') || 'http://localhost:5173',
      },
    });

    // Grant Lambda permissions to generate presigned URLs
    this.attachmentsBucket.grantReadWrite(this.presignedUrlFunction);

    // API Gateway with Cognito authorizer for presigned URL requests
    const appUrl = this.node.tryGetContext('appUrl') || 'http://localhost:5173';

    const authorizer = new apigateway.CognitoUserPoolsAuthorizer(this, 'PresignedUrlAuthorizer', {
      cognitoUserPools: [props.userPool],
    });

    const api = new apigateway.RestApi(this, 'PresignedUrlApi', {
      restApiName: 'AgentEchelon Presigned URL API',
      description: 'Authenticated API for generating S3 presigned URLs',
      defaultCorsPreflightOptions: {
        allowOrigins: [appUrl],
        allowMethods: ['POST', 'OPTIONS'],
        allowHeaders: ['Content-Type', 'Authorization'],
      },
      deployOptions: {
        throttlingBurstLimit: 50,
        throttlingRateLimit: 25,
        // Access logging.
        ...apiAccessLogConfig(this, 'PresignedUrlApiAccessLogs'),
      },
    });

    const presignedUrlIntegration = new apigateway.LambdaIntegration(this.presignedUrlFunction);
    api.root.addResource('presigned-url').addMethod('POST', presignedUrlIntegration, {
      authorizer,
      authorizationType: apigateway.AuthorizationType.COGNITO,
    });

    // Outputs
    new cdk.CfnOutput(this, 'AttachmentsBucketName', {
      value: this.attachmentsBucket.bucketName,
      description: 'S3 bucket for file attachments',
      exportName: `${this.stackName}-BucketName`,
    });

    new cdk.CfnOutput(this, 'PresignedUrlApiUrl', {
      value: `${api.url}presigned-url`,
      description: 'API Gateway URL for presigned URL generation',
      exportName: `${this.stackName}-PresignedUrlApiUrl`,
    });

    cdk.Tags.of(this).add('Component', 'S3Storage');
  }
}
